[package]
name = "pci-ids-rs"
description = "Rust wrappers for the PCI ID Repository"
license = "MIT"
version = "0.3.0"
authors = ["Rafael Passos <rafael@rcpassos.me>", "William Woodruff <william@yossarian.net>", "Charles Lien <lienching31240@gmail.com>"]
edition = "2024"
readme = "README.md"
homepage = "https://github.com/auyer/pci-ids.rs"
repository = "https://github.com/auyer/pci-ids.rs"
keywords = ["pci"]
# minimum Rust version required
rust-version = "1.85"

categories = ["hardware-support"]

[build-dependencies]
nom = { version = "8.0", default-features = false }
phf_codegen = "0.14"
quote = "1.0"
proc-macro2 = "1.0"

[dependencies]
phf = { version = "0.14", default-features = false }

[badges]
maintenance = { status = "actively-developed" }

[package.metadata.release]
no-dev-version = true
disable-publish = true # handled by GitHub Actions
