name: check for updates to pci.ids
on:
  schedule:
    - cron: "0 12 * * *"
  push:
    branches:
      - remove-build-time-curl-fetch

permissions: {}

jobs:
  check-pciids:
    runs-on: ubuntu-latest
    permissions:
      contents: write # for create-pull-request
      pull-requests: write # for create-pull-request
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: try to update pci.ids
        run: |
          bash scripts/update-pciids.sh

      - name: create PR
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          commit-message: "[BOT] update pci.ids"
          branch: update-pciids
          title: "[BOT] update pci.ids"
          body: |
            This is an automated pull request, updating `pci.ids` after a detected change.

            Please review manually before merging.
          assignees: "auyer"
          reviewers: "auyer"
